### PR TITLE
Clear zap session

### PR DESCRIPTION
**Pull request by insideou7**
Zap persists scan results between sessions, so if you fix an issue and re-scan the application, Zap will return the non-existent issue. This PR adds a control option to clear the Zap session before the scan starts. It is enabled by default.

### CODE REVIEW

**Comment by kasunkv** [comment]
@insideou7 Can you please update this branch with the current changes to the master branch and update the PR. Then I will  approve and get a version released. Thanks for the contribution :)

**Comment by insideou7** [comment]
Done

**Comment by jabteles** [comment]
I think I need this "Clear ZAP Session" feature, do you know when it will be available? Regards

**Review by kasunkv — APPROVED** [review]

**Review by kasunkv — APPROVED** [review]
Approved.

**Pull request merged**
