### PR TITLE
Fix issue filter

### PR DESCRIPTION
**Pull request by insideou7**
Currently issues are filtered down to anything that matches the same host name, but if you have multiple websites on different context roots (eg http://test.com/site1 and http://test.com/site2) all the issues get lumped together. This PR filters down to just the base URL passed in to the scanner and includes only its children.

### CODE REVIEW

**Comment by kasunkv** [comment]
@insideou7 Can you please update this branch with the current changes to the master branch and update the PR. Then I will  approve and get a version released. Thanks for the contribution :)

**Comment by insideou7** [comment]
Done

**Comment by insideou7** [comment]
Closing- this fix only works for HTML reports, and the modified code is not called when generating XML or MD reports. It is called, however, when the report summary is generated. This means an XML report could have and issue on 'test.com/robots.txt' for a scan on 'test.com/contextroot/' and the result summary will say 0 issues found because one is filtered and one is not. I'll need to update to correct the results from each result type.

**Comment by kasunkv** [comment]
Hi @insideou7 Sorry for the delayed response. Will you be able to make the update you suggested in the last comment. If so please do it and update the PR. I'll be happy to merge the changes in. THanks for the contribution.

**Pull request closed without merging**
