### PR TITLE
fix "Cannot read property 'riskcode' of undefined"

### PR DESCRIPTION
**Pull request by insideou7**
Fixes the following:

#27 
#25 
#21 
#16 
#12

### CODE REVIEW

**Comment by izvictor** [comment]
Hello,
We are currently having the same issue, when are you planing to merge the request ?

**Comment by kasunkv** [comment]
@insideou7 @izvictor I will work on getting this PRs merged and a new version released by the end of the weekend. I need to do some changes to the CI pipeline and how I release these new versions. I will work on that during the weekend. Sorry for the delay.

**Comment by andydkelly-ig** [comment]
Thanks @kasunkv appreciate you getting back to us. Looking forward to the fix 👍

**Comment by jodachecallan** [comment]
@kasunkv Any progress on getting this PR complete?

**Comment by kasunkv** [comment]
@insideou7 Thanks for the contribution :) Finally got some time to setup the CI process for the repo. Can you please update this branch with the current changes to the master branch and update the PR. Then I will  approve and get a version released. Sorry for the delay in response.

**Comment by insideou7** [comment]
Done

**Review by kasunkv — APPROVED** [review]
Approved

**Pull request merged**
